name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - main



jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore
        run:  dotnet restore ./GithubActionsDemo.sln

      - name: Build
        run: dotnet build ./GithubActionsDemo.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./GithubActionsDemo.sln --configuration Release --no-build
        
